=== xkarl007/Kino-online/Lukas_Karasek.xsd
<!-- Odkaz na github: https://github.com/xkarl007/Kino-online -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="KinoOnline_konfigurace">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ob-nast">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="uvodni-stranka"/>
              <xs:element type="jazyko" name="jazyk"/>
              <xs:element type="charseto" name="charset"/>
              <xs:element type="xs:integer" name="google-id"/>
              <xs:element type="protokolo" name="protokol"/>
              <xs:element type="zapnuto" name="RSS-export"/>
              <xs:element type="zapnuto" name="tlacitko-facebook"/>
              <xs:element type="zapnuto" name="vyhledavani-host"/>
              <xs:element type="zapnuto" name="vyhledavani-uzivatel"/>
              <xs:element type="xs:string" name="denni-rezim-schema"/>
              <xs:element type="xs:string" name="nocni-rezim-schema"/>
              <xs:element type="zapnuto" name="robots"/>
              <xs:element type="zapnuto" name="ochrana-roboti"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="tabulka-oprav">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="opravneni" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:integer" name="id-opravneni"/>
                    <xs:element type="zapnuto" name="program-cteni"/>
                    <xs:element type="zapnuto" name="program-rezervace"/>
                    <xs:element type="zapnuto" name="vip-rezervace"/>
                    <xs:element type="zapnuto" name="program-editace"/>
                    <xs:element type="zapnuto" name="online-sledovani"/>
                    <xs:element type="zapnuto" name="detail-filmu-cteni"/>
                    <xs:element type="zapnuto" name="hodnoceni-filmu"/>
                    <xs:element type="zapnuto" name="komentare"/>
                    <xs:element type="zapnuto" name="narok-slevy" minOccurs="0"/>
                    <xs:element type="zapnuto" name="sprava-uzivatelu"/>
                    <xs:element type="zapnuto" name="sprava-komentaru"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="oprnazev" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="karty-nastaveni">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="karta" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:integer" name="cena-karty"/>
                    <xs:element type="xs:integer" name="doba-platnosti"/>
                    <xs:element type="koeficient" name="koeficient-kreditu"/>
                    <xs:element type="xs:integer" name="limit-kreditu"/>
                    <xs:element type="xs:integer" name="dalsi-level"/>
                    <xs:element type="zapnuto" name="VIP-vstup"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="knazev" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="film-nastaveni">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nazev-filmu"/>
              <xs:element type="xs:integer" name="id-filmu"/>
              <xs:element type="titulkyo" name="titulky"/>
              <xs:element type="dabingo" name="dabing"/>
              <xs:element type="datumo" name="datum-zverejneni"/>
              <xs:element type="vek-om" name="vek-omezeni"/>
              <xs:element type="xs:integer" name="delka-minut"/>
              <xs:element type="zapnuto" name="trojrozmerne"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="online-nastaveni">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="titulkyo" name="titulky"/>
              <xs:element type="kvalitao" name="kvalita"/>
              <xs:element type="mod" name="mod-prehravani"/>
              <xs:element type="hlasitosto" name="hlasitost"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Nastavení omezení -->
  <xs:simpleType name="zapnuto"> <!-- Omezení zapnuto/vypnuto 0/1 -->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="koeficient"> <!-- Omezení 1-100 -->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="jazyko"> <!-- Omezení nastavení jazyku -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="Čeština"/>
      <xs:enumeration value="Angličtina"/>
      <xs:enumeration value="Ruština"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="charseto"> <!-- Omezení nastavení charsetu -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="utf-7"/>
      <xs:enumeration value="windows-1258"/>
      <xs:enumeration value="utf-8"/>
      <xs:enumeration value="iso-8859"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="protokolo"> <!-- Omezení nastavení protokolů -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="http"/>
      <xs:enumeration value="https"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="titulkyo"> <!-- Omezení nastavení titulek -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="Žádné"/>
      <xs:enumeration value="České"/>
      <xs:enumeration value="Anglické"/>
      <xs:enumeration value="Ruské"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="dabingo"> <!-- Omezení nastavení dabingu -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="Český"/>
      <xs:enumeration value="Anglický"/>
      <xs:enumeration value="Ruský"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="kvalitao"> <!-- Omezení nastavení kvality obrazu u online přehrávání -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="HD"/>
      <xs:enumeration value="720 px"/>
      <xs:enumeration value="256 px"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="vek-om"> <!-- Omezení nastavení věku 0-18 -->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="18"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="mod"> <!-- Omezení nastavení módu přehrávání u online přehrávání -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="html5"/>
      <xs:enumeration value="Flash"/>
      <xs:enumeration value="Java"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hlasitosto"> <!-- Omezení nastavení hlasitosti u online přehrávání -->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="120"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="datumo"> <!-- Omezení nastavení datumu pro Český formát -->
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}"/>
      <xs:length value="10"/>
      </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== xkarl007/Kino-online/Lukas_Karasek.xml
<?xml version="1.0" encoding="UTF-8"?> 
  <?xml-stylesheet type="text/xsl" href="Lukas_Karasek.xsl"?>
  <!-- Odkaz na github: https://github.com/xkarl007/Kino-online --> 
<KinoOnline_konfigurace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Lukas_Karasek.xsd">

<!-- Obecné nastavení aplikace -->
<ob-nast>	
	<uvodni-stranka>index.php</uvodni-stranka>
	<jazyk>Čeština</jazyk>
	<charset>utf-8</charset>
	<google-id>1972</google-id>
	<protokol>https</protokol>
	<RSS-export>1</RSS-export>	
	<tlacitko-facebook>1</tlacitko-facebook>
	<vyhledavani-host>1</vyhledavani-host>
	<vyhledavani-uzivatel>1</vyhledavani-uzivatel>
	<denni-rezim-schema>/css/den.css</denni-rezim-schema>
	<nocni-rezim-schema>/css/noc.css</nocni-rezim-schema>
	<robots>1</robots>
	<ochrana-roboti>0</ochrana-roboti>
</ob-nast>

<!-- Nastavení oprávnění uživatelů -->
<tabulka-oprav>
	<opravneni oprnazev="host">
		<id-opravneni>0</id-opravneni>
		<program-cteni>1</program-cteni>
		<program-rezervace>0</program-rezervace>
		<vip-rezervace>0</vip-rezervace>
		<program-editace>0</program-editace>
		<online-sledovani>0</online-sledovani>
		<detail-filmu-cteni>1</detail-filmu-cteni>
		<hodnoceni-filmu>0</hodnoceni-filmu>
		<komentare>0</komentare>
		<sprava-uzivatelu>0</sprava-uzivatelu>
		<sprava-komentaru>0</sprava-komentaru>
	</opravneni>
	<opravneni oprnazev="registrovany">
		<id-opravneni>1</id-opravneni>
		<program-cteni>1</program-cteni>
		<program-rezervace>1</program-rezervace>
		<vip-rezervace>0</vip-rezervace>
		<program-editace>0</program-editace>
		<online-sledovani>1</online-sledovani>
		<detail-filmu-cteni>1</detail-filmu-cteni>
		<hodnoceni-filmu>1</hodnoceni-filmu>
		<komentare>1</komentare>
		<narok-slevy>1</narok-slevy>
		<sprava-uzivatelu>0</sprava-uzivatelu>
		<sprava-komentaru>0</sprava-komentaru>
	</opravneni>
	<opravneni oprnazev="VIP">
		<id-opravneni>2</id-opravneni>
		<program-cteni>1</program-cteni>
		<program-rezervace>1</program-rezervace>
		<vip-rezervace>1</vip-rezervace>
		<program-editace>0</program-editace>
		<online-sledovani>1</online-sledovani>
		<detail-filmu-cteni>1</detail-filmu-cteni>
		<hodnoceni-filmu>1</hodnoceni-filmu>
		<komentare>1</komentare>
		<narok-slevy>1</narok-slevy>
		<sprava-uzivatelu>0</sprava-uzivatelu>
		<sprava-komentaru>0</sprava-komentaru>
	</opravneni>
	<opravneni oprnazev="zamestnanec">
		<id-opravneni>3</id-opravneni>
		<program-cteni>1</program-cteni>
		<program-rezervace>1</program-rezervace>
		<vip-rezervace>1</vip-rezervace>
		<program-editace>1</program-editace>
		<online-sledovani>1</online-sledovani>
		<detail-filmu-cteni>1</detail-filmu-cteni>
		<hodnoceni-filmu>1</hodnoceni-filmu>
		<komentare>1</komentare>
		<narok-slevy>1</narok-slevy>
		<sprava-uzivatelu>0</sprava-uzivatelu>
		<sprava-komentaru>1</sprava-komentaru>
	</opravneni>
	<opravneni oprnazev="admin">
		<id-opravneni>4</id-opravneni>
		<program-cteni>1</program-cteni>
		<program-rezervace>1</program-rezervace>
		<vip-rezervace>1</vip-rezervace>
		<program-editace>1</program-editace>
		<online-sledovani>1</online-sledovani>
		<detail-filmu-cteni>1</detail-filmu-cteni>
		<hodnoceni-filmu>1</hodnoceni-filmu>
		<komentare>1</komentare>
		<narok-slevy>0</narok-slevy>
		<sprava-uzivatelu>1</sprava-uzivatelu>
		<sprava-komentaru>1</sprava-komentaru>
	</opravneni>
</tabulka-oprav>

<!-- Nastavení karet -->
<karty-nastaveni>
	<karta knazev="Standart">
		<cena-karty>60</cena-karty>
		<doba-platnosti>12</doba-platnosti>
		<koeficient-kreditu>5</koeficient-kreditu>
		<limit-kreditu>100</limit-kreditu>
		<dalsi-level>40</dalsi-level>
		<VIP-vstup>0</VIP-vstup>
	</karta>
	<karta knazev="Silver">
		<cena-karty>0</cena-karty>
		<doba-platnosti>24</doba-platnosti>
		<koeficient-kreditu>15</koeficient-kreditu>
		<limit-kreditu>500</limit-kreditu>
		<dalsi-level>60</dalsi-level>
		<VIP-vstup>0</VIP-vstup>
	</karta>
	<karta knazev="Golden">
		<cena-karty>0</cena-karty>
		<doba-platnosti>24</doba-platnosti>
		<koeficient-kreditu>25</koeficient-kreditu>
		<limit-kreditu>1000</limit-kreditu>
		<dalsi-level>0</dalsi-level>
		<VIP-vstup>0</VIP-vstup>
	</karta>
	<karta knazev="VIP">
		<cena-karty>800</cena-karty>
		<doba-platnosti>12</doba-platnosti>
		<koeficient-kreditu>29</koeficient-kreditu>
		<limit-kreditu>1500</limit-kreditu>
		<dalsi-level>0</dalsi-level>
		<VIP-vstup>1</VIP-vstup>
	</karta>
</karty-nastaveni>

<!-- Nastavení filmů obecné -->
<film-nastaveni>
	<nazev-filmu>Test film</nazev-filmu>
	<id-filmu>0</id-filmu>
	<titulky>České</titulky>
	<dabing>Anglický</dabing>
	<datum-zverejneni>01.01.2017</datum-zverejneni>
	<vek-omezeni>0</vek-omezeni>
	<delka-minut>75</delka-minut>
	<trojrozmerne>0</trojrozmerne>
</film-nastaveni>

<!-- Nastavení online sledovaní -->
<online-nastaveni>
	<titulky>Žádné</titulky>
	<kvalita>HD</kvalita>
	<mod-prehravani>html5</mod-prehravani>
	<hlasitost>100</hlasitost>
 </online-nastaveni>

</KinoOnline_konfigurace>
